packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalog: null

catalogMode: prefer

catalogs:
  build:
    tsdown: ^0.18.3
  deps:
    '@standard-schema/spec': ^1.1.0
    automd: ^0.4.2
    bumpp: ^10.3.2
    jiti: ^2.6.1
    rimraf: ^6.1.2
    tinyglobby: ^0.2.15
    typescript: ^5.9.3
    zod: ^4.2.1
  lint:
    '@antfu/eslint-config': ^6.7.3
    '@eslint-react/eslint-plugin': ^2.4.0
    eslint: ^9.39.2
    eslint-plugin-astro: 1.3.1
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.26
    eslint-plugin-solid: ^0.14.5
    eslint-plugin-svelte: 3.13.1
    lint-staged: ^16.2.7
    prettier-plugin-astro: 0.14.1
    simple-git-hooks: ^2.13.1
  playground:
    '@astrojs/check': ^0.9.6
    '@astrojs/react': ^4.4.2
    '@astrojs/solid-js': ^5.1.3
    '@astrojs/starlight': ^0.37.1
    '@astrojs/svelte': ^7.2.4
    '@astrojs/vue': ^5.1.3
    '@iconify-json/lucide': ^1.2.82
    '@tanstack/react-form': ^1.27.6
    '@tanstack/solid-form': ^1.27.7
    '@tanstack/svelte-form': ^1.27.7
    '@tanstack/vue-form': ^1.27.6
    '@unocss/postcss': ^66.5.10
    astro: ^5.16.6
    sharp: ^0.34.5
    unocss: ^66.5.10
    vee-validate: 5.0.0-beta.0
  test:
    '@vitest/coverage-v8': ^4.0.16
    tinyexec: ^1.0.2
    vitest: ^4.0.16
    vitest-package-exports: ^1.1.1
    yaml: ^2.8.2
  types:
    '@types/node': ^25.0.3
    type-fest: ^5.3.1

cleanupUnusedCatalogs: true

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
  - vite@6.4.1
