packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalog:

catalogMode: prefer

catalogs:
  build:
    tsdown: ^0.17.0
  deps:
    '@standard-schema/spec': ^1.0.0
    automd: ^0.4.2
    bumpp: ^10.3.2
    es-toolkit: ^1.42.0
    jiti: ^2.6.1
    rimraf: ^6.1.2
    tinyglobby: ^0.2.15
    typescript: ^5.9.3
    zod: ^4.1.13
  lint:
    '@antfu/eslint-config': ^6.4.2
    '@eslint-react/eslint-plugin': ^2.3.12
    eslint: ^9.39.1
    eslint-plugin-astro: 1.3.1
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.24
    lint-staged: ^16.2.7
    prettier-plugin-astro: 0.14.1
    simple-git-hooks: ^2.13.1
  playground:
    '@astrojs/react': ^4.4.2
    '@astrojs/vue': ^5.1.3
    '@tanstack/vue-form': ^1.27.1
    astro: ^5.16.4
    '@astrojs/starlight': ^0.37.1
    sharp: ^0.34.5
  test:
    '@vitest/coverage-v8': ^4.0.15
    vitest: ^4.0.15
  types:
    '@types/node': ^24.10.1
    type-fest: ^5.3.1

cleanupUnusedCatalogs: true

shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
  - vite@6.4.1
